language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy jacksondieter/reverseproxy:v1
  - docker tag udagram-api-user jacksondieter/udagram-api-user:v1
  - docker tag udagram-api-feed jacksondieter/udagram-api-feed:v1
  - docker tag udagram-frontend:local jacksondieter/udagram-frontend:v1

after_success:
  - echo "nothing needs to do"
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#   - docker push YOUR_DOCKER_HUB/simple-node
